import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { motion } from "framer-motion";
// Donut gauge 3D em alto relevo com degradê azul futurista
function DonutGauge({ value, max = 7, label }) {
    const size = 120;
    const stroke = 14;
    const r = (size - stroke) / 2;
    const circ = 2 * Math.PI * r;
    const pct = Math.min(value / max, 1);
    const offset = circ * (1 - pct);
    const gid = `gauge-grad-${label}-${value}`;
    const gidBg = `${gid}-bg`;
    const gidHi = `${gid}-hi`;
    return (_jsxs("div", { className: "relative flex items-center justify-center", style: { width: size, height: size }, children: [_jsxs("svg", { width: size, height: size, className: "-rotate-90", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: gid, x1: "0%", y1: "0%", x2: "100%", y2: "100%", children: [_jsx("stop", { offset: "0%", stopColor: "#38bdf8" }), _jsx("stop", { offset: "35%", stopColor: "#0ea5e9" }), _jsx("stop", { offset: "70%", stopColor: "#0369a1" }), _jsx("stop", { offset: "100%", stopColor: "#0c4a6e" })] }), _jsxs("linearGradient", { id: gidBg, x1: "0%", y1: "0%", x2: "100%", y2: "100%", children: [_jsx("stop", { offset: "0%", stopColor: "rgba(56,189,248,0.10)" }), _jsx("stop", { offset: "100%", stopColor: "rgba(12,74,110,0.18)" })] }), _jsxs("linearGradient", { id: gidHi, x1: "0%", y1: "0%", x2: "0%", y2: "100%", children: [_jsx("stop", { offset: "0%", stopColor: "rgba(255,255,255,0.45)" }), _jsx("stop", { offset: "50%", stopColor: "rgba(255,255,255,0)" }), _jsx("stop", { offset: "100%", stopColor: "rgba(0,0,0,0.25)" })] })] }), _jsx("circle", { cx: size / 2, cy: size / 2, r: r, fill: "none", stroke: `url(#${gidBg})`, strokeWidth: stroke }), _jsx("circle", { cx: size / 2, cy: size / 2 + 1.5, r: r, fill: "none", stroke: "rgba(0,0,0,0.12)", strokeWidth: stroke }), _jsx(motion.circle, { cx: size / 2, cy: size / 2, r: r, fill: "none", stroke: `url(#${gid})`, strokeWidth: stroke, strokeLinecap: "round", strokeDasharray: circ, initial: { strokeDashoffset: circ }, animate: { strokeDashoffset: offset }, transition: { duration: 0.9, ease: "easeOut" }, style: { filter: "drop-shadow(0 1px 2px rgba(3,105,161,0.5)) drop-shadow(0 0 6px rgba(14,165,233,0.4))" } }), _jsx(motion.circle, { cx: size / 2, cy: size / 2, r: r, fill: "none", stroke: `url(#${gidHi})`, strokeWidth: stroke * 0.35, strokeLinecap: "round", strokeDasharray: circ, initial: { strokeDashoffset: circ }, animate: { strokeDashoffset: offset }, transition: { duration: 0.9, ease: "easeOut" }, style: { opacity: 0.6 } })] }), _jsxs("div", { className: "absolute inset-0 flex flex-col items-center justify-center", children: [_jsx("span", { className: "text-2xl font-extrabold text-[#0c4a6e] tabular-nums leading-none drop-shadow-sm", children: Math.round(value) }), _jsx("span", { className: "text-[8px] uppercase tracking-wider text-[#0369a1] mt-0.5 font-bold", children: label })] })] }));
}
function MiniStat({ label, value, unit }) {
    return (_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[9px] uppercase tracking-wider text-[#004d40] font-bold", children: label }), _jsxs("span", { className: "text-sm font-bold text-[#004d40] tabular-nums", children: [Math.round(value).toLocaleString("pt-BR"), _jsx("span", { className: "text-[9px] text-[#004d40] ml-0.5 font-semibold", children: unit })] })] }));
}
export default function MaquinaGaugeCard({ maquina, rotatividade, setup, produtivo, dias, index = 0 }) {
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 18, scale: 0.97 }, animate: { opacity: 1, y: 0, scale: 1 }, transition: { delay: index * 0.08, duration: 0.45, ease: "easeOut" }, className: "relative overflow-hidden rounded-2xl border border-[#b2dfdb] bg-[#f0fdf9] p-3 shadow-[0_2px_16px_-4px_rgba(0,121,140,0.25)]", children: [_jsx("div", { className: "absolute -top-10 -right-10 w-28 h-28 rounded-full bg-[#00796b]/10 blur-3xl" }), _jsx("div", { className: "absolute bottom-0 left-0 h-0.5 w-full bg-gradient-to-r from-transparent via-[#00796b]/40 to-transparent" }), _jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-base font-extrabold text-[#004d40] tracking-tight", children: maquina }), _jsx("span", { className: "text-[10px] uppercase tracking-wider text-[#004d40] font-bold", children: "Esta\u00E7\u00E3o" })] }), _jsx(DonutGauge, { value: dias, label: "dias" })] }), _jsxs("div", { className: "grid grid-cols-3 gap-2 pt-2 border-t border-[#b2dfdb]", children: [_jsx(MiniStat, { label: "Rotativ.", value: rotatividade, unit: "m" }), _jsx(MiniStat, { label: "Setup", value: setup, unit: "min" }), _jsx(MiniStat, { label: "Produt.", value: produtivo, unit: "min" })] })] }));
}
