"use strict";
let freteTodos=[],freteFiltrados=[],fretePagina=1;
function inicializarSaldoFrete(){
 const ids=["freteBusca","freteStatus","freteEmpresa","freteDestinatario","freteRepresentante","freteInicio","freteFim","fretePorPagina"];
 ids.forEach(id=>{const e=document.getElementById(id);if(!e)return;e.addEventListener(e.type==="search"?"input":"change",()=>{fretePagina=1;aplicarFiltrosFrete()})});
 document.getElementById("btnLimparFrete")?.addEventListener("click",limparFiltrosFrete);
 document.getElementById("btnExportarFrete")?.addEventListener("click",exportarFrete);
 document.getElementById("freteAnterior")?.addEventListener("click",()=>{if(fretePagina>1){fretePagina--;renderizarFrete()}});
 document.getElementById("freteProxima")?.addEventListener("click",()=>{if(fretePagina<totalPaginasFrete()){fretePagina++;renderizarFrete()}});
 const botao=document.getElementById("btnCarregarFrete"),input=document.getElementById("inputPlanilhaFrete");
 botao?.addEventListener("click",()=>input?.click());
 input?.addEventListener("change",async()=>{const arq=input.files?.[0];if(!arq)return;try{botao.disabled=true;statusFrete("Processando a planilha de fretes...","");freteTodos=await processarPlanilhaFrete(arq);preencherFiltrosFrete();fretePagina=1;aplicarFiltrosFrete();statusFrete(`${freteTodos.length} registros de frete importados.`,"sucesso")}catch(err){console.error(err);statusFrete(err.message||"Não foi possível importar a planilha de fretes.","erro")}finally{botao.disabled=false;input.value=""}});
}
function statusFrete(msg,tipo){const box=document.getElementById("statusImportacaoFrete"),txt=document.getElementById("textoStatusFrete");if(!box||!txt)return;box.hidden=false;box.classList.remove("sucesso","erro");if(tipo)box.classList.add(tipo);txt.textContent=msg}
function normalizarCabFrete(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ")}
function acharIndiceFrete(headers,aliases){const norm=headers.map(normalizarCabFrete);for(const a of aliases){const i=norm.indexOf(normalizarCabFrete(a));if(i>=0)return i}return -1}
function valorCelula(linha,i){return i>=0?linha[i]:""}
function dataFrete(v){if(!v)return null;if(v instanceof Date&&!isNaN(v))return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?new Date(d.y,d.m-1,d.d):null}const s=String(v).trim();let m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return new Date(y,Number(m[2])-1,Number(m[1]))}const d=new Date(s);return isNaN(d)?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function numeroFrete(v){if(typeof v==="number")return isFinite(v)?v:0;let s=String(v??"").trim();if(!s)return 0;s=s.replace(/R\$\s?/g,"").replace(/\s/g,"");if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");return Number(s)||0}
async function processarPlanilhaFrete(arquivo){if(typeof XLSX==="undefined")throw new Error("Biblioteca do Excel não carregada.");const wb=XLSX.read(await arquivo.arrayBuffer(),{type:"array",cellDates:true});let escolhido=null;
 for(const nome of wb.SheetNames){const linhas=XLSX.utils.sheet_to_json(wb.Sheets[nome],{header:1,defval:"",raw:true});for(let r=0;r<Math.min(linhas.length,20);r++){const h=linhas[r]||[];const nota=acharIndiceFrete(h,["Nota Fiscal","NF","N.F."]);const venc=acharIndiceFrete(h,["Vencimento"]);const dest=acharIndiceFrete(h,["Destinatário","Destinatario","Cliente"]);const val=acharIndiceFrete(h,["Beneficiamento","Mão de Obra","Mao de Obra","Valor Frete","Frete"]);if(nota>=0&&venc>=0&&dest>=0&&val>=0){const score=(normalizarCabFrete(nome)==="planilha2"?100:0)+linhas.length; if(!escolhido||score>escolhido.score)escolhido={nome,linhas,cab:r,score}}}}
 if(!escolhido)throw new Error('Não encontrei as colunas de frete esperadas (Nota Fiscal, Destinatário, Vencimento e Beneficiamento/Mão de Obra).');
 const h=escolhido.linhas[escolhido.cab];const idx={empresa:acharIndiceFrete(h,["Empresa"]),nf:acharIndiceFrete(h,["Nota Fiscal","NF"]),emissao:acharIndiceFrete(h,["Emissão","Emissao"]),dest:acharIndiceFrete(h,["Destinatário","Destinatario","Cliente"]),rep:acharIndiceFrete(h,["Representante"]),desc:acharIndiceFrete(h,["Descrição","Descricao"]),valor:acharIndiceFrete(h,["Beneficiamento","Mão de Obra","Mao de Obra","Valor Frete","Frete"]),venc:acharIndiceFrete(h,["Vencimento"]),pag:acharIndiceFrete(h,["Data de pagamento","Data pagto","Pagamento"]),aberto:acharIndiceFrete(h,["Valor em Aberto","Valor em Aberto ","Em aberto Valor"]),obs:acharIndiceFrete(h,["Observação:","Observação","OBS"])};
 const hoje=new Date();hoje.setHours(0,0,0,0);return escolhido.linhas.slice(escolhido.cab+1).map((l,n)=>{const nf=valorCelula(l,idx.nf),valor=numeroFrete(valorCelula(l,idx.valor)),dest=String(valorCelula(l,idx.dest)||"").trim();if(!nf&&!valor&&!dest)return null;const venc=dataFrete(valorCelula(l,idx.venc)),pag=dataFrete(valorCelula(l,idx.pag));let aberto=numeroFrete(valorCelula(l,idx.aberto));if(pag)aberto=0;else if(!aberto)aberto=valor;const atraso=!pag&&venc&&venc<hoje;return{linha:n+escolhido.cab+2,empresa:String(valorCelula(l,idx.empresa)||"").trim(),nota:String(nf||"").trim(),emissao:dataFrete(valorCelula(l,idx.emissao)),destinatario:dest,representante:String(valorCelula(l,idx.rep)||"").trim(),descricao:String(valorCelula(l,idx.desc)||"").trim(),valor,vencimento:venc,pagamento:pag,aberto,observacao:String(valorCelula(l,idx.obs)||"").trim(),situacao:pag?"pago":atraso?"atrasado":"aberto"}}).filter(Boolean)}
function preencherSelectFrete(id,valores){const s=document.getElementById(id);if(!s)return;const atual=s.value;s.innerHTML='<option value="">Todos</option>';[...new Set(valores.map(v=>String(v||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR")).forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;s.appendChild(o)});if([...s.options].some(o=>o.value===atual))s.value=atual}
function preencherFiltrosFrete(){preencherSelectFrete("freteEmpresa",freteTodos.map(x=>x.empresa));preencherSelectFrete("freteDestinatario",freteTodos.map(x=>x.destinatario));preencherSelectFrete("freteRepresentante",freteTodos.map(x=>x.representante))}
function aplicarFiltrosFrete(){const busca=normalizarTexto(document.getElementById("freteBusca")?.value||""),status=document.getElementById("freteStatus")?.value||"",empresa=document.getElementById("freteEmpresa")?.value||"",dest=document.getElementById("freteDestinatario")?.value||"",rep=document.getElementById("freteRepresentante")?.value||"",ini=lerDataInput("freteInicio"),fim=lerDataInput("freteFim");freteFiltrados=freteTodos.filter(x=>{const txt=normalizarTexto([x.empresa,x.nota,x.destinatario,x.representante,x.descricao,x.observacao].join(" "));if(busca&&!txt.includes(busca))return false;if(status&&x.situacao!==status)return false;if(empresa&&x.empresa!==empresa)return false;if(dest&&x.destinatario!==dest)return false;if(rep&&x.representante!==rep)return false;if(ini&&(!x.vencimento||inicioDoDia(x.vencimento)<ini))return false;if(fim&&(!x.vencimento||inicioDoDia(x.vencimento)>fim))return false;return true});freteFiltrados.sort((a,b)=>(a.vencimento?.getTime?.()||0)-(b.vencimento?.getTime?.()||0));atualizarKpisFrete();renderizarFrete()}
function atualizarKpisFrete(){const pagos=freteFiltrados.filter(x=>x.situacao==="pago"),abertos=freteFiltrados.filter(x=>x.situacao!=="pago"),atrasados=freteFiltrados.filter(x=>x.situacao==="atrasado"),vencer=freteFiltrados.filter(x=>x.situacao==="aberto");const soma=(a,c)=>a+c;preencherTexto("freteKpiCarteira",formatarMoeda(freteFiltrados.map(x=>x.valor).reduce(soma,0)));preencherTexto("freteKpiAberto",formatarMoeda(abertos.map(x=>x.aberto).reduce(soma,0)));preencherTexto("freteKpiAtrasado",formatarMoeda(atrasados.map(x=>x.aberto).reduce(soma,0)));preencherTexto("freteKpiPago",formatarMoeda(pagos.map(x=>x.valor).reduce(soma,0)));preencherTexto("freteKpiVencer",formatarMoeda(vencer.map(x=>x.aberto).reduce(soma,0)));[["freteQtdCarteira",freteFiltrados.length],["freteQtdAberto",abertos.length],["freteQtdAtrasado",atrasados.length],["freteQtdPago",pagos.length],["freteQtdVencer",vencer.length]].forEach(([id,n])=>preencherTexto(id,`${n} títulos`));preencherTexto("freteResumo",`${freteFiltrados.length} de ${freteTodos.length} registros exibidos`)}
function totalPaginasFrete(){return Math.max(1,Math.ceil(freteFiltrados.length/Number(document.getElementById("fretePorPagina")?.value||25)))}
function renderizarFrete(){const corpo=document.getElementById("freteTabelaCorpo");if(!corpo)return;const por=Number(document.getElementById("fretePorPagina")?.value||25),paginas=totalPaginasFrete();fretePagina=Math.min(fretePagina,paginas);const itens=freteFiltrados.slice((fretePagina-1)*por,fretePagina*por);corpo.innerHTML=itens.length?itens.map(x=>`<tr><td>${escaparHtml(x.empresa||"—")}</td><td>${escaparHtml(x.nota||"—")}</td><td>${x.emissao?formatarDataBR(x.emissao):"—"}</td><td>${escaparHtml(x.destinatario||"—")}</td><td>${escaparHtml(x.representante||"—")}</td><td>${escaparHtml(x.descricao||"—")}</td><td>${x.vencimento?formatarDataBR(x.vencimento):"—"}</td><td>${x.pagamento?formatarDataBR(x.pagamento):"—"}</td><td><span class="frete-status ${x.situacao}">${x.situacao==="pago"?"Pago":x.situacao==="atrasado"?"Em atraso":"Em aberto"}</span></td><td class="frete-valor">${formatarMoeda(x.valor)}</td><td class="frete-valor ${x.aberto>0?"aberto":"pago"}">${formatarMoeda(x.aberto)}</td><td>${escaparHtml(x.observacao||"—")}</td></tr>`).join(""):'<tr><td colspan="12" class="frete-vazio">Nenhum registro encontrado.</td></tr>';preencherTexto("fretePaginaInfo",`Página ${fretePagina} de ${paginas}`);const a=document.getElementById("freteAnterior"),p=document.getElementById("freteProxima");if(a)a.disabled=fretePagina<=1;if(p)p.disabled=fretePagina>=paginas}
function limparFiltrosFrete(){["freteBusca","freteStatus","freteEmpresa","freteDestinatario","freteRepresentante","freteInicio","freteFim"].forEach(id=>{const e=document.getElementById(id);if(e)e.value=""});fretePagina=1;aplicarFiltrosFrete()}
function exportarFrete(){if(!freteFiltrados.length){alert("Não há registros de frete para exportar.");return}const linhas=[["Empresa","Nota Fiscal","Emissão","Destinatário","Representante","Descrição","Vencimento","Pagamento","Status","Valor Frete","Em aberto","Observação"],...freteFiltrados.map(x=>[x.empresa,x.nota,x.emissao?formatarDataBR(x.emissao):"",x.destinatario,x.representante,x.descricao,x.vencimento?formatarDataBR(x.vencimento):"",x.pagamento?formatarDataBR(x.pagamento):"",x.situacao,x.valor.toFixed(2).replace(".",","),x.aberto.toFixed(2).replace(".",","),x.observacao])];const csv=linhas.map(l=>l.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`saldo-frete-${formatarDataISO(new Date())}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
document.addEventListener("DOMContentLoaded",inicializarSaldoFrete);
