import { protegerModulo } from "../../../module-guard.js";
import { auth, db } from "../../../firebase-config.js";
import {
  collection, doc, getDocs, setDoc, deleteDoc, onSnapshot,
  serverTimestamp, writeBatch
} from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";

await protegerModulo("comex");

const COLLECTION = "comex_pj_desenvolvimentos";
const LOCAL_KEY = "smart_comex_pj_local_v1";
const DAY = 86400000;

const FIELD_DEFS = [
  {key:"diasProcesso", excel:"DIAS  EM PROCESSO", label:"DIAS EM PROCESSO", owner:"GERAL", type:"number", readonly:true},
  {key:"dataRecebimentoMaterial", excel:"DATA RECEBIMENTO CARTELA/ MATERIAL DO CLIENTE", label:"DATA RECEBIMENTO CARTELA/ MATERIAL DO CLIENTE", owner:"COMERCIAL", type:"date"},
  {key:"encaminhamentoEngenharia", excel:"ENCAMINHAMENTO PARA ENGENHARIA", label:"ENCAMINHAMENTO PARA ENGENHARIA", owner:"COMERCIAL", type:"date"},
  {key:"vencimentoComercial", excel:"VENCIMENTO", label:"VENCIMENTO", owner:"COMERCIAL", type:"date"},
  {key:"pj", excel:"PJ #", label:"PJ #", owner:"ENGENHARIA", type:"text", required:true},
  {key:"paisDestino", excel:"PAÍS DESTINO", label:"PAÍS DESTINO", owner:"ENGENHARIA", type:"text"},
  {key:"mesSolicitado", excel:"MÊS SOLICITADO", label:"MÊS SOLICITADO", owner:"ENGENHARIA", type:"text"},
  {key:"nomeMaterial", excel:"NOME DO MATERAIL DO PJ", label:"NOME DO MATERAIL DO PJ", owner:"ENGENHARIA", type:"text", required:true},
  {key:"caracteristicaMaterial", excel:"CARACTERÍSTICAMATERIAL", label:"CARACTERÍSTICAMATERIAL", owner:"ENGENHARIA", type:"text"},
  {key:"cor", excel:"COR", label:"COR", owner:"ENGENHARIA", type:"text"},
  {key:"siglaCliente", excel:"SIGLA CLIENTE", label:"SIGLA CLIENTE", owner:"ENGENHARIA", type:"text"},
  {key:"encaminhamentoComex", excel:"ENCAMINHAMENTO COMEX", label:"ENCAMINHAMENTO COMEX", owner:"ENGENHARIA", type:"date"},
  {key:"vencimentoEngenharia", excel:"VENCIMENTO", label:"VENCIMENTO", owner:"ENGENHARIA", type:"date"},
  {key:"aguardarEnvio", excel:"AGUARDAR ENVIO", label:"AGUARDAR ENVIO", owner:"CONTROLE", type:"select", options:["","SIM","NÃO"]},
  {key:"fedexAwbIda", excel:"FEDEX AWB", label:"FEDEX AWB", owner:"COMEX", type:"text"},
  {key:"dataEnvioDestino", excel:"DATA DE ENVIO PARA DESTINO", label:"DATA DE ENVIO PARA DESTINO", owner:"COMEX", type:"date"},
  {key:"dataRecebimentoDestino", excel:"DATA DE RECEBIMENTO NO DESTINO", label:"DATA DE RECEBIMENTO NO DESTINO", owner:"CHINA", type:"date"},
  {key:"fornecedor", excel:"FORNECEDOR", label:"FORNECEDOR", owner:"CHINA", type:"text"},
  {key:"somenteCotar", excel:"SOMENTE PARA COTAR", label:"SOMENTE PARA COTAR", owner:"CHINA", type:"select", options:["","SIM","NÃO"]},
  {key:"desenvolver", excel:"DESENVOLVER", label:"DESENVOLVER", owner:"CHINA", type:"select", options:["","SIM","NÃO"]},
  {key:"dataInicio", excel:"DATA INICIO", label:"DATA INICIO", owner:"CHINA", type:"date"},
  {key:"dataFim", excel:"DATA FIM", label:"DATA FIM", owner:"CHINA", type:"date"},
  {key:"fedexAwbVolta", excel:"FEDEX AWB", label:"FEDEX AWB", owner:"CHINA", type:"text"},
  {key:"dataEnvioBrasil", excel:"DATA ENVIO PARA O BRASIL", label:"DATA ENVIO PARA O BRASIL", owner:"CHINA", type:"date"},
  {key:"statusDestino", excel:"STATUS DESTINO", label:"STATUS DESTINO", owner:"CHINA", type:"text"},
  {key:"dataRecebimentoBrasil", excel:"DATA RECEBIMENTO NO BRASIL", label:"DATA RECEBIMENTO NO BRASIL", owner:"COMEX", type:"date"},
  {key:"dataEncaminhamentoEngenhariaFinal", excel:"DATA ENCAMINHAMENTO PARA ENGENHARIA", label:"DATA ENCAMINHAMENTO PARA ENGENHARIA", owner:"COMEX", type:"date"},
  {key:"dataEntregueComercial", excel:"DATA ENTREGUE PARA COMERCIAL", label:"DATA ENTREGUE PARA COMERCIAL", owner:"ENGENHARIA", type:"date"},
  {key:"retornoComercial", excel:"RETORNO DO COMERCIAL", label:"RETORNO DO COMERCIAL", owner:"COMERCIAL", type:"text"},
  {key:"statusFinal", excel:"STATUS FINAL DO PJ", label:"STATUS FINAL DO PJ", owner:"COMERCIAL", type:"text"}
];

const SECTIONS = [
  {id:"geral", title:"Controle geral", owner:"GERAL", note:"Cálculo automático", keys:["diasProcesso"]},
  {id:"comercial1", title:"1. Comercial", owner:"COMERCIAL", note:"Prazo D+1", keys:["dataRecebimentoMaterial","encaminhamentoEngenharia","vencimentoComercial"]},
  {id:"engenharia1", title:"2. Engenharia", owner:"ENGENHARIA", note:"Prazo 2 dias", keys:["pj","paisDestino","mesSolicitado","nomeMaterial","caracteristicaMaterial","cor","siglaCliente","encaminhamentoComex","vencimentoEngenharia"]},
  {id:"controle", title:"Controle de envio", owner:"CONTROLE", note:"Campo da planilha entre Engenharia e COMEX", keys:["aguardarEnvio"]},
  {id:"comex1", title:"3. COMEX", owner:"COMEX", note:"Prazo até 7 dias", keys:["fedexAwbIda","dataEnvioDestino"]},
  {id:"china", title:"4. China / Fornecedor", owner:"CHINA", note:"Trânsito estimado 10 dias · desenvolvimento estimado 15 dias", keys:["dataRecebimentoDestino","fornecedor","somenteCotar","desenvolver","dataInicio","dataFim","fedexAwbVolta","dataEnvioBrasil","statusDestino"]},
  {id:"comex2", title:"5. COMEX", owner:"COMEX", note:"Retorno ao Brasil estimado em 10 dias", keys:["dataRecebimentoBrasil","dataEncaminhamentoEngenhariaFinal"]},
  {id:"engenharia2", title:"6. Engenharia", owner:"ENGENHARIA", note:"Entrega do material ao Comercial", keys:["dataEntregueComercial"]},
  {id:"comercial2", title:"7. Comercial", owner:"COMERCIAL", note:"Retorno e encerramento do PJ", keys:["retornoComercial","statusFinal"]}
];

const TIMELINE = [
  {id:"commercial", label:"Comercial", complete:r=>!!r.encaminhamentoEngenharia, start:r=>r.dataRecebimentoMaterial, due:r=>r.vencimentoComercial || addDaysString(r.dataRecebimentoMaterial,1)},
  {id:"engineering", label:"Engenharia", complete:r=>!!r.encaminhamentoComex, start:r=>r.encaminhamentoEngenharia, due:r=>r.vencimentoEngenharia || addDaysString(r.encaminhamentoEngenharia,2)},
  {id:"comex-out", label:"COMEX", complete:r=>!!r.dataEnvioDestino, start:r=>r.encaminhamentoComex, due:r=>addDaysString(r.encaminhamentoComex,7)},
  {id:"china-arrival", label:"China · Recebimento", complete:r=>!!r.dataRecebimentoDestino, start:r=>r.dataEnvioDestino, due:r=>addDaysString(r.dataEnvioDestino,10)},
  {id:"china-development", label:"China · Desenvolvimento", complete:r=>!!r.dataFim || !!r.dataEnvioBrasil, start:r=>r.dataInicio || r.dataRecebimentoDestino, due:r=>addDaysString(r.dataInicio || r.dataRecebimentoDestino,15)},
  {id:"return", label:"Retorno Brasil", complete:r=>!!r.dataRecebimentoBrasil, start:r=>r.dataEnvioBrasil, due:r=>addDaysString(r.dataEnvioBrasil,10)},
  {id:"comex-return", label:"COMEX", complete:r=>!!r.dataEncaminhamentoEngenhariaFinal, start:r=>r.dataRecebimentoBrasil, due:r=>null},
  {id:"engineering-final", label:"Engenharia", complete:r=>!!r.dataEntregueComercial, start:r=>r.dataEncaminhamentoEngenhariaFinal, due:r=>null},
  {id:"commercial-final", label:"Comercial", complete:r=>isCompleted(r), start:r=>r.dataEntregueComercial, due:r=>null}
];

const $ = s => document.querySelector(s);
const state = {records:[], filtered:[], selected:null, mode:"connecting", unsubscribe:null};

function normalize(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase()}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function dateObj(s){if(!s)return null;const d=new Date(`${String(s).slice(0,10)}T12:00:00`);return isNaN(d)?null:d}
function today(){const d=new Date();d.setHours(12,0,0,0);return d}
function dateString(d){if(!d)return "";const x=new Date(d);if(isNaN(x))return "";return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function addDaysString(s,n){const d=dateObj(s);if(!d)return "";d.setDate(d.getDate()+n);return dateString(d)}
function diffDays(a,b){const x=dateObj(a),y=dateObj(b);if(!x||!y)return 0;return Math.max(0,Math.floor((y-x)/DAY))}
function formatDate(s){const d=dateObj(s);return d?d.toLocaleDateString("pt-BR"):"—"}
function valueText(v){return v===null||v===undefined||v===""?"—":String(v)}
const COUNTRY_FLAG_MAP={"china":"🇨🇳","china continental":"🇨🇳","italia":"🇮🇹","italy":"🇮🇹","vietna":"🇻🇳","vietnam":"🇻🇳","india":"🇮🇳","turquia":"🇹🇷","turkey":"🇹🇷","brasil":"🇧🇷","brazil":"🇧🇷","paraguai":"🇵🇾","paraguay":"🇵🇾","uruguai":"🇺🇾","uruguay":"🇺🇾","chile":"🇨🇱","argentina":"🇦🇷","peru":"🇵🇪","colombia":"🇨🇴","equador":"🇪🇨","ecuador":"🇪🇨","bolivia":"🇧🇴","venezuela":"🇻🇪","mexico":"🇲🇽","estados unidos":"🇺🇸","eua":"🇺🇸","usa":"🇺🇸","canada":"🇨🇦","portugal":"🇵🇹","espanha":"🇪🇸","spain":"🇪🇸","franca":"🇫🇷","france":"🇫🇷","alemanha":"🇩🇪","germany":"🇩🇪","reino unido":"🇬🇧","inglaterra":"🇬🇧","uk":"🇬🇧","holanda":"🇳🇱","paises baixos":"🇳🇱","belgica":"🇧🇪","suica":"🇨🇭","polonia":"🇵🇱","suecia":"🇸🇪","dinamarca":"🇩🇰","noruega":"🇳🇴","finlandia":"🇫🇮","grecia":"🇬🇷","romenia":"🇷🇴","russia":"🇷🇺","japao":"🇯🇵","coreia do sul":"🇰🇷","coreia":"🇰🇷","taiwan":"🇹🇼","indonesia":"🇮🇩","paquistao":"🇵🇰","bangladesh":"🇧🇩","malasia":"🇲🇾","singapura":"🇸🇬","tailandia":"🇹🇭","filipinas":"🇵🇭","emirados arabes unidos":"🇦🇪","emirados arabes":"🇦🇪","arabia saudita":"🇸🇦","israel":"🇮🇱","egito":"🇪🇬","africa do sul":"🇿🇦","australia":"🇦🇺","nova zelandia":"🇳🇿"};
function countryFlag(country){const key=normalize(country);return COUNTRY_FLAG_MAP[key]||""}
function countryLabel(country){const txt=valueText(country);if(txt==="—")return txt;const flag=countryFlag(country);return flag?`${flag} ${txt}`:txt}
function updateCountryPreview(){const input=$("[name=paisDestino]");const preview=$("#countryPreview");if(!preview)return;const value=input?.value?.trim()||"";preview.textContent=value?countryLabel(value):"Bandeira automática";preview.classList.toggle("active",!!value)}
function displayFieldValue(field, raw){if(field?.key==="paisDestino")return countryLabel(raw);return field?.type==="date"?formatDate(raw):valueText(raw)}
function isCompleted(r){const s=normalize(r.statusFinal);return !!s && !["andamento","em andamento","aguardando","pendente"].includes(s)}
function currentStage(r){if(isCompleted(r))return {index:TIMELINE.length-1,label:"Concluído",sector:"COMERCIAL",stage:TIMELINE.at(-1)};for(let i=0;i<TIMELINE.length;i++){if(!TIMELINE[i].complete(r)){const label=TIMELINE[i].label;const sector=label.startsWith("China")?"CHINA":label.includes("Retorno Brasil")?"COMEX":label.toUpperCase().includes("ENGENHARIA")?"ENGENHARIA":label.toUpperCase().includes("COMEX")?"COMEX":"COMERCIAL";return {index:i,label,sector,stage:TIMELINE[i]}}}return {index:TIMELINE.length-1,label:"Comercial",sector:"COMERCIAL",stage:TIMELINE.at(-1)}}
function totalDays(r){const start=r.dataRecebimentoMaterial;if(!start)return 0;let end=dateString(today());if(isCompleted(r))end=r.dataEntregueComercial||r.dataRecebimentoBrasil||r.dataFim||end;return diffDays(start,end)}
function stageDays(r){const c=currentStage(r);const start=c.stage.start(r);return start?diffDays(start,dateString(today())):0}
function deadlineStatus(r){if(isCompleted(r))return {label:"Concluído",css:"done",due:"",days:0};const c=currentStage(r);const due=c.stage.due(r);if(!due)return {label:"No prazo",css:"ontime",due:"",days:0};const delta=Math.ceil((dateObj(due)-today())/DAY);if(delta<0)return {label:"Atrasado",css:"late",due,days:Math.abs(delta)};if(delta<=2)return {label:"Em risco",css:"risk",due,days:delta};return {label:"No prazo",css:"ontime",due,days:delta}}
function updatedLabel(r){if(r.updatedAt?.toDate)return r.updatedAt.toDate().toLocaleDateString("pt-BR");if(r.updatedAt)return new Date(r.updatedAt).toLocaleDateString("pt-BR");return "—"}
function docIdFor(r){const base=(r.pj||`pj-${Date.now()}`).toString().trim().replace(/[^\w-]+/g,"-");return base||`pj-${Date.now()}`}
function userLabel(){return auth.currentUser?.email||auth.currentUser?.displayName||"Usuário Analytics"}
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
function setSync(mode){state.mode=mode;const el=$("#syncBadge");if(mode==="online"){el.className="sync-badge online";el.innerHTML='<i class="fa-solid fa-circle"></i> Firestore conectado'}else if(mode==="local"){el.className="sync-badge local";el.innerHTML='<i class="fa-solid fa-circle"></i> Modo local — publicar regra do COMEX PJ'}else{el.className="sync-badge neutral";el.innerHTML='<i class="fa-solid fa-circle"></i> Conectando…'}}
function normalizeRecord(data,id){const r={id,...data};FIELD_DEFS.forEach(f=>{if(r[f.key]===undefined)r[f.key]=""});r.diasProcesso=totalDays(r);r.historico=Array.isArray(r.historico)?r.historico:[];return r}

async function connectData(){setSync("connecting");try{const ref=collection(db,COLLECTION);await getDocs(ref);state.unsubscribe=onSnapshot(ref,snap=>{state.records=snap.docs.map(d=>normalizeRecord(d.data(),d.id));refresh();setSync("online")},err=>{console.warn(err);loadLocal()});setSync("online")}catch(err){console.warn("COMEX PJ Firestore indisponível; usando modo local.",err);loadLocal()}}
function loadLocal(){setSync("local");try{const raw=JSON.parse(localStorage.getItem(LOCAL_KEY)||"[]");state.records=raw.map(r=>normalizeRecord(r,r.id));refresh()}catch{state.records=[];refresh()}}
function persistLocal(){localStorage.setItem(LOCAL_KEY,JSON.stringify(state.records.map(r=>({...r,updatedAt:r.updatedAt||new Date().toISOString()}))))}
async function saveRecord(record){record.diasProcesso=totalDays(record);record.updatedBy=userLabel();const event={data:new Date().toISOString(),usuario:userLabel(),acao:record.id?"Desenvolvimento atualizado":"Desenvolvimento criado"};record.historico=[...(record.historico||[]).slice(-39),event];if(state.mode==="online"){const id=record.id||docIdFor(record);const payload={...record,id:undefined,updatedAt:serverTimestamp()};delete payload.id;await setDoc(doc(db,COLLECTION,id),payload,{merge:true});record.id=id}else{if(!record.id)record.id=docIdFor(record);record.updatedAt=new Date().toISOString();const ix=state.records.findIndex(r=>r.id===record.id);if(ix>=0)state.records[ix]=normalizeRecord(record,record.id);else state.records.push(normalizeRecord(record,record.id));persistLocal();refresh()}showToast("Desenvolvimento salvo com sucesso.")}
async function removeRecord(id){if(state.mode==="online")await deleteDoc(doc(db,COLLECTION,id));else{state.records=state.records.filter(r=>r.id!==id);persistLocal();refresh()}showToast("Desenvolvimento excluído.")}

function renderForm(){const byKey=Object.fromEntries(FIELD_DEFS.map(f=>[f.key,f]));$("#formSections").innerHTML=SECTIONS.map(section=>`<section class="form-section"><div class="form-section-head"><h3>${escapeHtml(section.title)}</h3><span>${escapeHtml(section.note)}</span></div><div class="fields">${section.keys.map(k=>fieldHtml(byKey[k])).join("")}</div></section>`).join("");const b=$("[name=dataRecebimentoMaterial]");const c=$("[name=encaminhamentoEngenharia]");const country=$("[name=paisDestino]");b?.addEventListener("change",()=>{const d=$("[name=vencimentoComercial]");if(d&&!d.value)d.value=addDaysString(b.value,1);const m=$("[name=mesSolicitado]");if(m&&!m.value&&b.value)m.value=String(dateObj(b.value).getMonth()+1);updateLiveDays()});c?.addEventListener("change",()=>{const d=$("[name=vencimentoEngenharia]");if(d&&!d.value)d.value=addDaysString(c.value,2);updateLiveDays()});country?.addEventListener("input",updateCountryPreview);updateCountryPreview()}
function fieldHtml(f){const req=f.required?"required":"";const ro=f.readonly?"readonly":"";let control;if(f.type==="select")control=`<select name="${f.key}">${f.options.map(o=>`<option value="${escapeHtml(o)}">${escapeHtml(o||"Selecione")}</option>`).join("")}</select>`;else control=`<input name="${f.key}" type="${f.type||"text"}" ${req} ${ro}>`;if(f.key==="paisDestino")control=`<div class="country-field">${control}<div id="countryPreview" class="country-preview">Bandeira automática</div></div>`;return `<div class="field ${["nomeMaterial","caracteristicaMaterial"].includes(f.key)?"wide":""}"><label>${escapeHtml(f.label)}</label>${control}</div>`}
function updateLiveDays(){const start=$("[name=dataRecebimentoMaterial]")?.value;const el=$("[name=diasProcesso]");if(el)el.value=start?diffDays(start,dateString(today())):0}
function openModal(record=null){renderForm();$("#pjForm").reset();$("#recordId").value=record?.id||"";$("#modalTitle").textContent=record?`Editar ${record.pj||"PJ"}`:"Novo Desenvolvimento";FIELD_DEFS.forEach(f=>{const el=$(`[name=${f.key}]`);if(el)el.value=record?.[f.key]??""});if(record)$("[name=diasProcesso]").value=totalDays(record);updateLiveDays();updateCountryPreview();$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function formRecord(){const existing=state.records.find(r=>r.id===$("#recordId").value);const r=existing?{...existing}:{historico:[]};FIELD_DEFS.forEach(f=>{const el=$(`[name=${f.key}]`);if(el&&!f.readonly)r[f.key]=el.value.trim()});r.id=$("#recordId").value||"";r.diasProcesso=totalDays(r);return r}

function filterRecords(){const q=normalize($("#searchInput").value);const stage=$("#stageFilter").value;const deadline=$("#deadlineFilter").value;const country=$("#countryFilter").value;state.filtered=state.records.filter(r=>{const hay=normalize([r.pj,r.nomeMaterial,r.siglaCliente,r.fornecedor,r.cor,r.paisDestino].join(" "));if(q&&!hay.includes(q))return false;if(stage&&currentStage(r).label!==stage)return false;if(deadline&&deadlineStatus(r).label!==deadline)return false;if(country&&r.paisDestino!==country)return false;return true})}
function refreshFilters(){const stages=[...new Set(state.records.map(r=>currentStage(r).label))].sort();const countries=[...new Set(state.records.map(r=>r.paisDestino).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));const s=$("#stageFilter"),c=$("#countryFilter");const sv=s.value,cv=c.value;s.innerHTML='<option value="">Todas as etapas</option>'+stages.map(x=>`<option>${escapeHtml(x)}</option>`).join("");c.innerHTML='<option value="">Todos os países</option>'+countries.map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(countryLabel(x))}</option>`).join("");s.value=sv;c.value=cv}
function refresh(){refreshFilters();filterRecords();renderKpis();renderCharts();renderTable();if(state.selected){const found=state.records.find(r=>r.id===state.selected.id);if(found){state.selected=found;renderDetail(found)}else closeDetail()}}
function renderKpis(){const rs=state.records;const stats=rs.map(deadlineStatus);const count=l=>stats.filter(s=>s.label===l).length;$("#kpiTotal").textContent=rs.length;$("#kpiLate").textContent=count("Atrasado");$("#kpiRisk").textContent=count("Em risco");$("#kpiOnTime").textContent=count("No prazo");$("#kpiDone").textContent=count("Concluído");$("#kpiLatePct").textContent=`${rs.length?Math.round(count("Atrasado")/rs.length*100):0}% do total`;$("#kpiOnTimePct").textContent=`${rs.length?Math.round(count("No prazo")/rs.length*100):0}% do total`;const avg=rs.length?Math.round(rs.reduce((a,r)=>a+totalDays(r),0)/rs.length):0;$("#kpiAvg").textContent=`${avg} dias`}
function renderCharts(){const rs=state.records;const groups=[['Atrasado','#e43d3d'],['Em risco','#eaa21a'],['No prazo','#14a865'],['Concluído','#0b76f0']];let acc=0;const stops=[];groups.forEach(([name,color])=>{const n=rs.filter(r=>deadlineStatus(r).label===name).length;const p=rs.length?n/rs.length*100:0;stops.push(`${color} ${acc}% ${acc+p}%`);acc+=p});if(acc<100)stops.push(`#e5ebf2 ${acc}% 100%`);$("#statusDonut").style.background=`conic-gradient(${stops.join(",")})`;$("#donutTotal").textContent=rs.length;$("#statusLegend").innerHTML=groups.map(([name,color])=>{const n=rs.filter(r=>deadlineStatus(r).label===name).length;return `<div class="legend-row"><span class="legend-dot" style="background:${color}"></span><span>${name}</span><strong>${n}</strong></div>`}).join("");renderBars("#stageBars",countBy(rs,r=>currentStage(r).label),6);renderBars("#countryBars",countBy(rs,r=>r.paisDestino||"Sem país"),6)}
function countBy(rows,fn){const m=new Map();rows.forEach(r=>{const k=fn(r);m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function renderBars(sel,items,limit){const el=$(sel);const top=items.slice(0,limit);const max=Math.max(1,...top.map(x=>x[1]));const isCountry=sel==="#countryBars";el.innerHTML=top.length?top.map(([name,n])=>{const label=isCountry?countryLabel(name):name;return `<div class="bar-row"><span title="${escapeHtml(label)}">${escapeHtml(label)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(5,n/max*100)}%"></div></div><strong>${n}</strong></div>`}).join(""):'<div class="empty-state show" style="padding:30px 10px"><p>Sem dados</p></div>'}
function renderTable(){filterRecords();const body=$("#rows");$("#resultCount").textContent=`${state.filtered.length} registro(s)`;$("#emptyState").classList.toggle("show",state.filtered.length===0);body.innerHTML=state.filtered.map(r=>{const d=deadlineStatus(r),c=currentStage(r);return `<tr data-id="${escapeHtml(r.id)}"><td><span class="alert-icon ${d.css}"><i class="fa-solid ${d.css==='late'?'fa-exclamation':d.css==='risk'?'fa-clock':d.css==='done'?'fa-flag-checkered':'fa-check'}"></i></span></td><td><strong>${escapeHtml(r.pj||"—")}</strong></td><td>${escapeHtml(r.nomeMaterial||"—")}</td><td><span class="country-chip">${escapeHtml(countryLabel(r.paisDestino))}</span></td><td>${escapeHtml(r.siglaCliente||"—")}</td><td><strong>${escapeHtml(c.sector)}</strong><br><span class="stage-label">${escapeHtml(c.label)}</span></td><td>${stageDays(r)}</td><td>${totalDays(r)}</td><td><span class="status-pill ${d.css}">${d.label}${d.due?` · ${formatDate(d.due)}`:""}</span></td><td>${updatedLabel(r)}</td><td><button class="action-btn edit-row" data-id="${escapeHtml(r.id)}" title="Editar"><i class="fa-solid fa-pen"></i></button><button class="action-btn view-row" data-id="${escapeHtml(r.id)}" title="Detalhar"><i class="fa-regular fa-eye"></i></button></td></tr>`}).join("");body.querySelectorAll("tr").forEach(tr=>tr.addEventListener("click",e=>{if(e.target.closest("button"))return;openDetail(tr.dataset.id)}));body.querySelectorAll(".edit-row").forEach(b=>b.addEventListener("click",()=>openModal(state.records.find(r=>r.id===b.dataset.id))));body.querySelectorAll(".view-row").forEach(b=>b.addEventListener("click",()=>openDetail(b.dataset.id)))}

function openDetail(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.selected=r;renderDetail(r);$("#detailPanel").classList.remove("hidden");$("#detailPanel").scrollIntoView({behavior:"smooth",block:"start"})}
function closeDetail(){state.selected=null;$("#detailPanel").classList.add("hidden")}
function renderDetail(r){const d=deadlineStatus(r),c=currentStage(r);$("#detailPj").textContent=r.pj||"Sem PJ";$("#detailMaterial").textContent=r.nomeMaterial||"—";$("#detailAlert").className=`alert-dot ${d.css}`;$("#detailStatus").className=`status-pill ${d.css}`;$("#detailStatus").textContent=d.label;$("#detailDays").textContent=`${totalDays(r)} dias em processo`;$("#detailDeadline").textContent=d.due?`Prazo ${formatDate(d.due)}`:`Etapa ${c.label}`;$("#generalInfo").innerHTML=infoDl([['País destino',countryLabel(r.paisDestino)],['Mês solicitado',r.mesSolicitado],['Cliente',r.siglaCliente],['Cor',r.cor],['Característica',r.caracteristicaMaterial],['Fornecedor',r.fornecedor],['Setor atual',c.sector],['Atualizado por',r.updatedBy]]);renderTimeline(r,d,c);$("#processInfo").innerHTML=SECTIONS.filter(s=>s.id!=="geral").map(s=>`<div class="process-group"><div class="process-group-head"><span>${escapeHtml(s.title)}</span><span>${escapeHtml(s.note)}</span></div><div class="process-group-body">${s.keys.map(k=>{const f=FIELD_DEFS.find(x=>x.key===k);return `<div class="process-field"><span>${escapeHtml(f.label)}</span><strong>${escapeHtml(displayFieldValue(f,r[k]))}</strong></div>`}).join("")}</div></div>`).join("");const hist=[...(r.historico||[])].reverse();$("#historyList").innerHTML=hist.length?hist.map(h=>`<div class="history-item"><strong>${escapeHtml(h.acao||"Atualização")}</strong><span>${new Date(h.data).toLocaleString("pt-BR")} · ${escapeHtml(h.usuario||"Usuário")}</span></div>`).join(""):'<p style="color:#8090a1;font-size:10px">Sem histórico registrado.</p>'}
function infoDl(items){return items.map(([k,v])=>`<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(valueText(v))}</dd>`).join("")}
function renderTimeline(r,d,current){$("#timeline").innerHTML=TIMELINE.map((s,i)=>{const complete=s.complete(r);const cls=complete?"complete":i===current.index?(d.css==='late'?"late":"current"):"";const date=complete?timelineCompletionDate(r,s.id):(i===current.index?s.start(r):"");return `<div class="timeline-step ${cls}"><div class="timeline-dot"></div><strong>${escapeHtml(s.label)}</strong><span>${date?formatDate(date):complete?'Concluído':i===current.index?'Em andamento':'Pendente'}</span></div>`}).join("");const n=$("#deadlineNotice");n.className=`deadline-notice ${d.css==='late'?'late':d.css==='risk'?'risk':''}`;if(d.label==='Atrasado')n.textContent=`Este desenvolvimento está ${d.days} dia(s) atrasado na etapa “${current.label}”. Prazo: ${formatDate(d.due)}.`;else if(d.label==='Em risco')n.textContent=`A etapa “${current.label}” vence em ${d.days} dia(s), em ${formatDate(d.due)}.`;else if(d.label==='Concluído')n.textContent="Desenvolvimento concluído conforme o Status Final do PJ.";else n.textContent=d.due?`Etapa “${current.label}” dentro do prazo. Prazo atual: ${formatDate(d.due)}.`:`Etapa “${current.label}” em andamento, sem prazo explícito na planilha.`}
function timelineCompletionDate(r,id){return ({commercial:r.encaminhamentoEngenharia,engineering:r.encaminhamentoComex,"comex-out":r.dataEnvioDestino,"china-arrival":r.dataRecebimentoDestino,"china-development":r.dataFim||r.dataEnvioBrasil,return:r.dataRecebimentoBrasil,"comex-return":r.dataEncaminhamentoEngenhariaFinal,"engineering-final":r.dataEntregueComercial,"commercial-final":r.dataEntregueComercial})[id]||""}

function excelDate(value){if(value===""||value==null)return "";if(value instanceof Date&&!isNaN(value))return dateString(value);if(typeof value==="number"&&window.XLSX?.SSF){const p=XLSX.SSF.parse_date_code(value);if(p)return `${p.y}-${String(p.m).padStart(2,"0")}-${String(p.d).padStart(2,"0")}`}const s=String(value).trim();const m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return `${y}-${String(m[2]).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}`}return s.match(/^\d{4}-\d{2}-\d{2}/)?.[0]||""}
async function importExcel(file){if(!window.XLSX)throw new Error("Biblioteca Excel não carregada.");const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:"array",cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const matrix=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:""});const headerIndex=matrix.findIndex(row=>row.some(v=>normalize(v)==="pj #"));if(headerIndex<0)throw new Error('Não encontrei a linha de cabeçalho com "PJ #".');const rows=matrix.slice(headerIndex+1).filter(row=>row.some(v=>String(v??"").trim()!==""));const records=rows.map(row=>{const r={historico:[{data:new Date().toISOString(),usuario:userLabel(),acao:`Importado de ${file.name}`}]};FIELD_DEFS.forEach((f,i)=>{if(f.readonly)return;const v=row[i]??"";r[f.key]=f.type==="date"?excelDate(v):String(v??"").trim()});r.diasProcesso=totalDays(r);return r}).filter(r=>r.pj||r.nomeMaterial);if(!records.length)throw new Error("Nenhum desenvolvimento válido foi encontrado.");if(state.mode==="online"){for(let i=0;i<records.length;i+=450){const batch=writeBatch(db);records.slice(i,i+450).forEach(r=>{const id=docIdFor(r);batch.set(doc(db,COLLECTION,id),{...r,updatedBy:userLabel(),updatedAt:serverTimestamp()},{merge:true})});await batch.commit()}}else{records.forEach(r=>{r.id=docIdFor(r);r.updatedBy=userLabel();r.updatedAt=new Date().toISOString();const ix=state.records.findIndex(x=>x.id===r.id);if(ix>=0)state.records[ix]=normalizeRecord(r,r.id);else state.records.push(normalizeRecord(r,r.id))});persistLocal();refresh()}showToast(`${records.length} desenvolvimento(s) importado(s).`)}
function exportExcel(){const rows=[[],["","PRAZO D+1","","","PRAZO 2 DIAS","","","","","","","","","","PRAZO ATÉ 7 DIAS"],["","COMERCIAL","","","ENGENHARIA","","","","","","","","","","COMEX","","CHINA","","","","","","","","","COMEX","","ENGENHARIA","COMERCIAL",""] ,FIELD_DEFS.map(f=>f.excel),["","","","","","","","","","","","","","","","ESTIMADO EM 10 DIAS","","ESTIMADO EM 15 DIAS","","","","","","","","ESTIMADO EM 10 DIAS"],[],[]];state.records.forEach(r=>rows.push(FIELD_DEFS.map(f=>f.key==="diasProcesso"?totalDays(r):r[f.key]||"")));const ws=XLSX.utils.aoa_to_sheet(rows);ws["!merges"]=[XLSX.utils.decode_range("B2:D2"),XLSX.utils.decode_range("E2:M2"),XLSX.utils.decode_range("O2:P2"),XLSX.utils.decode_range("B3:D3"),XLSX.utils.decode_range("E3:M3"),XLSX.utils.decode_range("O3:P3"),XLSX.utils.decode_range("Q3:Y3"),XLSX.utils.decode_range("Z3:AA3"),XLSX.utils.decode_range("AC3:AD3"),XLSX.utils.decode_range("P5:Q5"),XLSX.utils.decode_range("R5:V5")];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Planilha1");XLSX.writeFile(wb,`COMEX_PJ_${dateString(today()).replaceAll('-','')}.xlsx`)}

$("#newButton").addEventListener("click",()=>openModal());$("#closeModal").addEventListener("click",closeModal);$("#cancelButton").addEventListener("click",closeModal);$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});$("#pjForm").addEventListener("submit",async e=>{e.preventDefault();try{await saveRecord(formRecord());closeModal()}catch(err){console.error(err);showToast(`Erro ao salvar: ${err.message||err}`)}});$("#closeDetail").addEventListener("click",closeDetail);$("#editButton").addEventListener("click",()=>state.selected&&openModal(state.selected));$("#deleteButton").addEventListener("click",async()=>{if(!state.selected)return;if(!confirm(`Excluir o desenvolvimento ${state.selected.pj||"selecionado"}?`))return;try{await removeRecord(state.selected.id);closeDetail()}catch(err){showToast(`Erro ao excluir: ${err.message||err}`)}});$("#importButton").addEventListener("click",()=>$("#fileInput").click());$("#fileInput").addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{await importExcel(f)}catch(err){console.error(err);showToast(err.message||"Falha ao importar Excel.")}finally{e.target.value=""}});$("#exportButton").addEventListener("click",exportExcel);["#searchInput","#stageFilter","#deadlineFilter","#countryFilter"].forEach(sel=>$(sel).addEventListener(sel==="#searchInput"?"input":"change",()=>{filterRecords();renderTable()}));

renderForm();await connectData();
